on:
  pull_request:
    branches:
      - master
name: Token List Generation
jobs: 
  generate_lists:
    name: Generate Token Lists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Node-js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'

      - name: Install Dependencies
        run: yarn install --ignore-engines

      - name: Build ./dist
        run: yarn build

      - name: CI Check
        run: yarn ci-check-auto
      
      - name: Generate Token List
        run: yarn generate-auto